### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by leannejdong** [LiaGroza/Graph-Algorithms#1]
DFS is one of the most important ones, please add :)

**Comment by LiaGroza** [comment]
Hi, Leanne! Thank you for your suggestion! You are totally right, but this repo was intended to host some of my solutions on classic graph problems and it will no longer have any updates. I've created another (more extended and continuously updating) repo with algorithms - DFS & BFS included. 
https://github.com/LiaGroza/Algorithms

**Comment by iuliagroza** [comment]
Hi, Leanne! Thank you for your suggestion! You are totally right, but this repo was intended to host some of my solutions on classic graph problems and it will no longer have any updates. I've created another (more extended and continuously updating) repo with algorithms - DFS & BFS included.
https://github.com/LiaGroza/Algorithms

**Comment by leannejdong** [comment]
Hi LiaGroza, nice work.
I modified your codes a bit. 
https://godbolt.org/z/ev9aKf
You can update it if you like my version :)
